### ISSUE TITLE
Date field filtering does not work in 8.9.0

### ISSUE THREAD

**Issue by Gustav-Coleske** [tieniber/DataGridColumnSearch#22]
Getting the error "window.mx.parser.delocalizeEpoch is not a function TypeError: window.mx.parser.delocalizeEpoch is not a function" when searching on date fields.
